Add controllers
f-berezyuk/java-shareit pull request #1
Opened 2024-09-01 22:45 UTC by f-berezyuk

2024-09-02 18:34 UTC, mikita95 requested changes
Все сделано отлично :) Оставил лишь небольшие замечания

2024-09-02 18:34 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +@Service
Это интерфейс, на нем эта аннотация не нужна :)

2024-09-02 18:34 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private ItemRepository repository;
Эти поля можно сделать final

2024-09-02 18:34 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/storage/ItemRepositoryImpl.java
> +    HashMap<Long, Item> internalStorage = new HashMap<>();
Не хватает модификаторов доступа :)

2024-09-03 07:49 UTC, f-berezyuk commented on src/main/java/ru/practicum/shareit/item/storage/ItemRepositoryImpl.java
> +    HashMap<Long, Item> internalStorage = new HashMap<>();
поправил)

2024-09-03 07:49 UTC, f-berezyuk commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    private ItemRepository repository;
сделал

2024-09-03 07:49 UTC, f-berezyuk commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +@Service
убрал))

2024-09-03 08:14 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-09-07 20:06 UTC, merged