add-item-requests-and-gateway
f-berezyuk/java-shareit pull request #3
Opened 2024-10-27 14:34 UTC by f-berezyuk

2024-10-28 11:51 UTC, mikita95 requested changes
Добрый день, все сделано отлично :) Оставил лишь косметические замечания

2024-10-28 11:51 UTC, mikita95 commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    ItemRequestClient itemRequestClient;
Можно сделать private final

2024-10-28 11:51 UTC, mikita95 commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    ItemRequestService requestService;
Поле лучше сделать private final

2024-10-28 11:51 UTC, mikita95 commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    AnswersRepository answersRepository;
Поля лучше сделать private final

2024-10-28 19:01 UTC, f-berezyuk commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    ItemRequestService requestService;
сделал

2024-10-28 19:01 UTC, f-berezyuk commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    ItemRequestClient itemRequestClient;
сделал

2024-10-28 19:01 UTC, f-berezyuk commented on server/src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    AnswersRepository answersRepository;
сделал

2024-10-29 19:54 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-10-30 06:13 UTC, merged